### ISSUE TITLE
note: zip::zip() is deprecated, please use zip::zipr() instead

### ISSUE THREAD

**Issue by a-bro-0227** [ycphs/openxlsx#15]
When writing xlsx files, i am getting the following:

note: zip::zip() is deprecated, please use zip::zipr() instead

here is an example:

```
library(openxlsx)

df <- data.frame(x = c(1, 2, 3), y = c("a", "b", "c"))

write.xlsx(df, file = "C:/Users/abrown_17/Desktop/df_test.xlsx", overwrite = T)
```

Thanks,
Alex

**Comment by ycphs** [comment]
Hi Alex,

Which version do you use?

**Comment by ycphs** [comment]
This message is corrected in the development version. 

```
install.packages(c("Rcpp", "devtools"), dependencies = TRUE)
require(devtools)
install_github("ycphs/openxlsx")
```

The code above should solve the issue.

**Comment by a-bro-0227** [comment]
Hi @ycphs thanks for your quick reply! i just updated to 4.1.3 and am still getting the issue but i'll try the development one.

**Comment by ycphs** [comment]
If the development version works, please close the issue.
