### ISSUE TITLE
Fix Excel file corruption when multiple data validation on a sheet

### ISSUE THREAD

**Issue by david-f1976** [ycphs/openxlsx#9]
Adding multiple data validation to a worksheet produces corrupt Excel 2016 files.

Original issue is here: [https://github.com/awalker89/openxlsx/issues/266](https://github.com/awalker89/openxlsx/issues/266) with test code in which tkunstek produced a pull request.

I have incorporated that particular commit into my own repository and it works ok. Bit of a git/github newbie, so can you look at pulling the relevant fix into this repository.

Thanks

**Comment by ycphs** [comment]
I managed to include the code. I hope that helped.

**Comment by ycphs** [comment]
@david-f1976 
Maybe you can change your repository so you can do a pull request directly here.

**Comment by david-f1976** [comment]
Thanks.

I only took that initial fix into my own repository as, at the time, it looked like development was dead, and it was something I needed fairly urgently.

I have re-installed your version from github and it looks like this is fixed. So am happy to follow your subsequent CRAN releases from now on to avoid duplicated codebases, at least for for the time being.

**Comment by bsleik** [comment]
I am using the current dev version 4.1.3 from the install_github("ycphs/openxlsx") (as of Nov 14th PM) and still experiencing this issue.  Maybe it isn't committed to the main dev code branch yet.  Published regular openxlsx version on Nov 14th PM also still had the issue.

**Comment by ycphs** [comment]
@bsleik could you please provide an example file and the minimal example to test the code?

**Comment by bsleik** [comment]
I will provide as soon as possible.  I created minimal version as requested, but it works fine with your current build.  My production code which is much larger fails with your build but works fine with the "tkunstek/openxlsx" 4.0.29 build.  When it doesn't work, I get the corrupted spreadsheet error.  I will anonymize my data and provide a sample corrupted document, then work on trying to simplify the code.

**Comment by ycphs** [comment]
@bsleik if the issue still exists, could you please provide a pull request?

**Comment by jtrecenti** [comment]
Hi ppl, I'm experiencing this issue. Here's a reprex.

[test.xlsx](https://github.com/ycphs/openxlsx/files/3875229/test.xlsx)


``` r
library(openxlsx)

wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")
da <- data.frame(x = c("", ""), y = c("s", "n"))
writeDataTable(wb, sheet = 1, x = da)
dataValidation(wb, 1, col = 1, rows = 2:3, type = "list", value = "a,b")
saveWorkbook(wb, "test.xlsx", overwrite = TRUE)
```

<sup>Created on 2019-11-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.1 (2019-07-05)
#>  os       Ubuntu 19.04                
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    pt_BR.UTF-8                 
#>  tz       America/Sao_Paulo           
#>  date     2019-11-21                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                         
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                 
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                 
#>  callr         3.3.2      2019-09-22 [1] CRAN (R 3.6.1)                 
#>  cli           1.1.0      2019-03-19 [1] CRAN (R 3.6.0)                 
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                 
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                 
#>  devtools      2.2.1      2019-09-24 [1] CRAN (R 3.6.1)                 
#>  digest        0.6.22     2019-10-21 [1] CRAN (R 3.6.1)                 
#>  ellipsis      0.3.0      2019-09-20 [1] CRAN (R 3.6.1)                 
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                 
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                 
#>  glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.1)                 
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)                 
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.1)                 
#>  knitr         1.26       2019-11-12 [1] CRAN (R 3.6.1)                 
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.0)                 
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                 
#>  openxlsx    * 4.1.3.9004 2019-11-21 [1] Github (ycphs/openxlsx@0bf4ae9)
#>  pkgbuild      1.0.6      2019-10-09 [1] CRAN (R 3.6.1)                 
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                 
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.6.0)                 
#>  processx      3.4.1      2019-07-18 [1] CRAN (R 3.6.0)                 
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                 
#>  R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.1)                 
#>  Rcpp          1.0.3      2019-11-08 [1] CRAN (R 3.6.1)                 
#>  remotes       2.1.0      2019-06-24 [1] CRAN (R 3.6.0)                 
#>  rlang         0.4.1      2019-10-24 [1] CRAN (R 3.6.1)                 
#>  rmarkdown     1.17       2019-11-13 [1] CRAN (R 3.6.1)                 
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.6.0)                 
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                 
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                 
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                 
#>  testthat      2.3.0      2019-11-05 [1] CRAN (R 3.6.1)                 
#>  usethis       1.5.1      2019-07-04 [1] CRAN (R 3.6.0)                 
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.0)                 
#>  xfun          0.11       2019-11-12 [1] CRAN (R 3.6.1)                 
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.6.0)                 
#>  zip           2.0.4      2019-09-01 [1] CRAN (R 3.6.1)                 
#> 
#> [1] /home/jt/R/x86_64-pc-linux-gnu-library/3.6
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

**Comment by ycphs** [comment]
Hi @jtrecenti,

According to the documentation that's the solution to your issue:

```library(openxlsx)

wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")
addWorksheet(wb, "validation")
da <- data.frame(x = c("", ""), y = c("s", "n"))
writeDataTable(wb, sheet = 1, x = da)
val<-data.frame(c1=c("a","b"))
writeDataTable(wb,sheet=2,x=val)
dataValidation(wb, 1, col = 1, rows = 2:3, type = "list", value = "'validation'!$A$2:$A$3")
saveWorkbook(wb, "test.xlsx", overwrite = TRUE)
```


I hope that solves your problem.

**Comment by SHAESEN2** [comment]
I am experiencing the same issue when I want to add two validations:

wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")
addWorksheet(wb, "validation")

writeDataTable(wb, sheet = 1, x = data.frame(x = c("", ""), y = c("", "")))

val<-data.frame(c1=c("a","b",""), c2=c("a2","b2", "c2"))
writeDataTable(wb,sheet=2,x=val)

dataValidation(wb, 1, col = 1, rows = 2:3, type = "list", value = "'validation'!$A$2:$A$3")
dataValidation(wb, 1, col = 2, rows = 2:3, type = "list", value = "'validation'!$B$2:$B$4")


saveWorkbook(wb, file.path(opath,"test.xlsx"), overwrite = TRUE)

Is there a fix for this or another way of implementing this?

**Comment by ycphs** [comment]
I tested your example. It works as it should.

If you open the xlsx in excel, the cells are marked, because of the data validation. What is your desired result of the data validation?

**Comment by SHAESEN2** [comment]
Hey,

I cloned the project and installed from there. Now it seems to work. Previously I used devtools::install_github("ycphs/openxlsx") which did gave me the corrupted file.
